service: nextjs-testing

plugins:
  - serverless-offline


provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 1536
  timeout: 30
  environment:

functions:
  nextJsApp:
    handler: lambda.handler
    events:
      - http:
          path: /{any+}
          method: ANY

resources:
  Description: Next.js testing in AWS lambda
